version: "3.8"

services:
  authentication:
    build:
      context: ./authentication
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./authentication:/app/
    env_file:
      - ./env/auth.env
  erp-backend:
    build:
      context: ./erp-backend
      dockerfile: ./Dockerfile
    ports:
      - 9090:9090
    volumes:
      - ./erp-backend:/app/
    env_file:
      - ./env/back.env
    depends_on:
      - authentication
