version: "3.8"

services:
  authentication:
    build:
      context: ./authentication
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./authentication:/app/
    env_file:
      - ./env/auth.env
  erp-backend:
    build:
      context: ./erp-backend
      dockerfile: ./Dockerfile
    ports:
      - 9090:9090
    volumes:
      - ./erp-backend:/app/
    env_file:
      - ./env/back.env
    depends_on:
      - authentication
  erp-frontend:
    build:
      context: ./erp-frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./erp-frontend:/app/
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - erp-backend
      - authentication
